core/urls.py
"""
This module specifies core URLs for the backend REST API and determines what views to match with them

"""

from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('check-email/', views.CheckEmail.as_view(), name='check_email'),
    path('communities/join/', views.JoinCommunity.as_view(), name='join_community'),
    path('communities/leave/', views.LeaveCommunity.as_view(), name='leave_community'),
    path('features/add-to-community/', views.AddFeatureToCommunity.as_view(), name='add_feature_to_community'),
    path('features/remove/', views.RemoveFeature.as_view(), name='remove_feature'),
    path('data-store/', views.DataStore.as_view(), name='data_store'),
    path('data-store/delete/<int:store_id>/', views.DataStoreDetails.as_view(), name='data_store_delete'),
    path('upload-img/', views.UploadImage.as_view(), name='upload_img'),
]

developer/urls.py
"""
This module specifies the developer website URLs and determines what views to match with them

"""

from django.urls import path

from developer import views

app_name = 'developer'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-feature/', views.add_feature, name='add_feature'),
    path('edit-feature/<int:feature_id>/', views.edit_feature, name='edit_feature'),
    path('feature-details/<int:feature_id>/', views.feature_details, name='feature_details'),
    path('delete-feature/<int:feature_id>/', views.delete_feature, name='delete_feature'),
]

mega_backend/urls.py
"""
mega_backend URL Configuration

The `urlpatterns` list routes URLs to views
"""
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from core import views as core_views, urls as core_urls

from accounts import views as accounts_views, urls as accounts_urls

from developer import urls as developer_urls

from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import RedirectView

# DRF router configuration

api_router = routers.DefaultRouter()
api_router.register(r'community-types', core_views.CommunityTypeViewSet, basename='community_type')
api_router.register(r'profiles', accounts_views.ProfileViewSet, basename='profile')
api_router.register(r'features', core_views.FeatureViewSet, basename='feature')
api_router.register(r'communities', core_views.CommunityViewSet, basename='community')

# the urls

urlpatterns = [
    path('api/', include(core_urls)),
    path('api/', include(api_router.urls)),
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('accounts/', include(accounts_urls)),
    path('developer/', include(developer_urls)),
    path('favicon.ico', RedirectView.as_view(url='/static/core/img/favicon.ico')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

developer/models.py
from django.db import models

# Create your models here.

developer/forms.py
from django import forms

from core.models import Feature

from django.utils.translation import ugettext_lazy as _


class FeatureForm(forms.ModelForm):
    """ Form for creating and editing feature """
    class Meta:
        model = Feature
        fields = ['name', 'picture', 'description', 'payload']

        labels = {
            'name': _('feature name'),
            'picture': _('feature picture'),
            'description': _('description'),
            'payload': _('feature code')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label

developer/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.urls import reverse

from core.models import Feature

from developer.forms import FeatureForm


# Create your views here.


@login_required
def index(request):
    """
    Home page view for developers

    Parameters
    ----------
    request

    Returns
    -------
    object
        Http response object

    """
    _features = request.user.features.all()

    ctx = {
        'features': _features
    }

    return render(request, 'developer/index.html', ctx)


@login_required
def feature_details(request, feature_id):
    """
    Feature details page

    Parameters
    ----------
    request
    feature_id : int
        The id of the feature

    Returns
    -------
    object
        Http response object

    """
    try:
        _feature = Feature.objects.get(pk=feature_id)
    except Feature.DoesNotExist:
        return redirect('developer:index')

    ctx = {
        'feature': _feature
    }

    return render(request, 'developer/feature_details.html', ctx)


@login_required
def add_feature(request):
    """
    Add feature

    Parameters
    ----------
    request

    Returns
    -------
    object
        Http response object
    """
    _feature_form = None

    if request.method == 'POST':
        _feature_form = FeatureForm(data=request.POST, files=request.FILES)

        if _feature_form.is_valid():
            _feature = _feature_form.save(commit=False)
            _feature.user = request.user
            _feature.save()
            return redirect('developer:index')
    else:
        _feature_form = FeatureForm()

    ctx = {
        'form': _feature_form
    }

    return render(request, 'developer/add_feature.html', ctx)


@login_required
def edit_feature(request, feature_id):
    """
    Edit feature

    Parameters
    ----------
    request
    feature_id : int
        The id of the feature

    Returns
    -------
    object
        Http response object
    """
    try:
        _feature = Feature.objects.get(pk=feature_id)
    except Feature.DoesNotExist:
        return redirect('developer:index')

    _feature_form = None

    if request.method == 'POST':
        _feature_form = FeatureForm(data=request.POST, files=request.FILES, instance=_feature)

        if _feature_form.is_valid():
            _feature = _feature_form.save()
            return redirect(reverse('developer:feature_details', kwargs={'feature_id': _feature.id}))
    else:
        _feature_form = FeatureForm(instance=_feature)

    ctx = {
        'form': _feature_form
    }

    return render(request, 'developer/edit_feature.html', ctx)


@login_required
def delete_feature(request, feature_id):
    """
    Delete feature

    Parameters
    ----------
    request
    feature_id : int
        The id of the feature

    Returns
    -------
    object
        Http response object
    """

    try:
        _feature = Feature.objects.get(pk=feature_id)
    except Feature.DoesNotExist:
        return redirect('developer:index')
    _feature.delete()
    return redirect(reverse('developer:index'))

developer/templates/developer/add_feature.html
{% extends 'core/base.html' %}

{% load form %}

{% block body %}
<div class="container">
    <div>
        <h3>Add Feature</h3>
    </div>

    {% form is_multipart=True %}
</div>
{% endblock %}

developer/templates/developer/edit_feature.html
{% extends 'core/base.html' %}

{% load form %}

{% block body %}
<div class="container">
    <div>
        <h3>Edit Feature</h3>
    </div>

    {% form is_multipart=True %}

</div>
{% endblock %}

developer/templates/developer/feature_details.html
{% extends 'core/base.html' %}

{% block title %}- feature details{% endblock %}

{% block body %}
<div class="container">
    <div>
        <h3>Feature details</h3>
    </div>
    <div>
        <img src="{{ MEDIA_URL }}{{ feature.picture.url }}" alt="Feature Image" class="width-18">
         <div class="mt-3">
             <div>
                 <h5>{{ feature.name }}</h5>
             </div>

             <div class="my-3">
                  <p class="mb-0">
                      {% if feature.approved == True %}
                      Approved
                      {% elif feature.approved == False %}
                      Rejected
                      {% else %}
                      Not evaluated
                      {% endif %}
                  </p>
                  <small>approval status</small>
             </div>

             <div class="my-3">
                 <p class="mb-0 border border-rounded p-2">{{ feature.description }}</p>
                 <small>description</small>
             </div>

             <div class="my-3">
                 <p class="mb-0 border border-rounded p-2">{{ feature.payload }}</p>
                 <small>code</small>
             </div>

              <div class="my-3">
                  <p class="mb-0">{{ feature.key }}</p>
                  <small>key</small>
             </div>

             <a href="{% url 'developer:edit_feature' feature.pk %}" class="btn btn-primary">Edit details</a>
             <a href="{% url 'developer:delete_feature' feature.pk %}" class="btn btn-danger">Delete feature</a>
        </div>
    </div>
</div>
{% endblock %}

developer/templates/developer/index.html
{% extends 'core/base.html' %}

{% block title %}- developer{% endblock %}

{% block body %}
<div class="container">
    <div>
        <h3>Your Features</h3>
    </div>
    <div class="row row-cols-1 row-cols-md-2 row-cols-md-3">
        {% for feature in features %}
        <div class="col mb-4">
            <div class="card width-18">

                <img src="{{ MEDIA_URL }}{{ feature.picture.url }}" class="card-img-top" alt="Feature Image">
                 <div class="card-body">
                    <h5 class="card-title">{{ feature.name }}</h5>
                    <p class="card-text text-truncate">{{ feature.description }}</p>
                    <a href="{% url 'developer:feature_details' feature.pk %}" class="btn btn-primary">View details</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-12 col-md-6 col-lg-4">
            <a href="{% url 'developer:add_feature' %}">
                <div class="card border-dashed width-18">
                    <span class="my-auto mx-auto">add feature</span>
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}